spring:
  application:
    name: gateway

  cloud:
    nacos:
      server-addr: 106.15.5.109:8848

    gateway:
      routes:
        - id: users_route
#          uri: http://localhost:8888
          uri: lb://user
          predicates:
            - Path=/user/**
